### ISSUE TITLE
Firestore & Storage rules?

### ISSUE THREAD

**Issue by voipworld** [Rezuanul-Islam-Fahim/hasper_ebook_admin#3]
Salam my brother,
thank you for this great & botyfull work.
may you please provide a ceparate json files for both storage & firestore rules?
thank you.

**Comment by Rezuanul-Islam-Fahim** [comment]
Walaikumussalam.

> Salam my brother, thank you for this great & botyfull work. may you please provide a ceparate json files for both storage & firestore rules? thank you.

There is no admin login. So, I've enabled permission for reading and writting without any condition.

**Comment by voipworld** [comment]
yes, but where do i enable this permitions?
dont i need ruls for storage & firestore?

**Comment by Rezuanul-Islam-Fahim** [comment]
https://youtu.be/b7PUm7LmAOw

This video can help you
